version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend_server
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    container_name: frontend_server
    ports:
      - "80:80"
